# Supported Assets Configuration
# This file defines all supported assets for the application
# Each asset can have different contract addresses per network
current_network: "TEST"
native_asset: "ETH"

# Network configuration
networks:
  # Test
  TEST: "test-url"
  # Local
  LOCAL: "http://localhost:8545"
  # Mainnet
  ETHEREUM: "https://ethereum-rpc.publicnode.com"
  ARBITRUM: "https://arbitrum-one-rpc.publicnode.com"
  BASE: "https://base-rpc.publicnode.com"
  # Testnet
  ETHEREUM_SEPOLIA: "https://ethereum-sepolia-rpc.publicnode.com"
  ARBITRUM_SEPOLIA: "https://arbitrum-sepolia-rpc.publicnode.com"
  BASE_SEPOLIA: "https://base-sepolia-rpc.publicnode.com"

# Assets configuration
assets:
  USDC:
    ETHEREUM: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
    ARBITRUM: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    BASE: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    ETHEREUM_SEPOLIA: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    ARBITRUM_SEPOLIA: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
    BASE_SEPOLIA: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"

  USDT:
    ETHEREUM: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    ARBITRUM: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
    BASE: "0xfde4c96c8593536e31f229ea8f37b2ada2699bb2" # Bridged USDT
    # ETHEREUM_SEPOLIA: "0x0000000000000000000000000000000000000000" # Unable to find official contract address
    # ARBITRUM_SEPOLIA: "0x0000000000000000000000000000000000000000" # Unable to find official contract address
    # BASE_SEPOLIA: "0x0000000000000000000000000000000000000000" # Unable to find official contract address

  SHIB:
    ETHEREUM: "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"
    BASE: "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"