services:
  api:
    image: "${CONTAINER_REGISTRY-localhost:5005}/mb:${VERSION-development}"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT-8000}
        - ENV=${ENV-dev}
        - SERVICE=api
        - VERSION=${VERSION-development}
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=${POSTGRES_PORT-1425}
        - POSTGRES_DB=${POSTGRES_DB-mb_db}
        - POSTGRES_USER=${POSTGRES_USER-mb_user}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mb_password}
        - DB_POOL_MIN_SIZE=${DB_POOL_MIN_SIZE-1}
        - DB_POOL_MAX_SIZE=${DB_POOL_MAX_SIZE-10}
        - DB_POOL_MAX_IDLE=${DB_POOL_MAX_IDLE-300}
        - DB_POOL_TIMEOUT=${DB_POOL_TIMEOUT-30}
    ports:
      - "${PORT-8000}:${PORT-8000}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mb-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:${PORT-8000}/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB-mb_db}
      - POSTGRES_USER=${POSTGRES_USER-mb_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mb_password}
    command: ["postgres", "-p", "${POSTGRES_PORT-1425}"]
    ports:
      - "${POSTGRES_PORT-1425}:${POSTGRES_PORT-1425}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mb-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER-mb_user} -p ${POSTGRES_PORT-1425} -d ${POSTGRES_DB-mb_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  mb-network:
    driver: bridge